name: github_coding_test
description: Coding test for CoDev

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  build_runner: ^2.3.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  flutter_localizations: 
    sdk: flutter 
  intl: any
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  riverpod_generator: ^2.1.4

flutter:
  uses-material-design: true
